FROM python:3.5
MAINTAINER Sergey Nuzhdin <ipaq.lw@gmail.com>

RUN mkdir -p '/opt/monetario/core'
VOLUME ['/opt/monetario/core']

WORKDIR /opt/monetario/core

ADD ./requirements-dev.txt /opt/requirements-core-dev.txt

RUN pip install -r /opt/requirements-core-dev.txt

EXPOSE 9000
