"""empty message

Revision ID: 13484841a0c
Revises: None
Create Date: 2016-03-09 11:54:39.334813

"""

# revision identifiers, used by Alembic.
revision = '13484841a0c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category_type', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_logo'), 'category', ['logo'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_index(op.f('ix_category_parent_id'), 'category', ['parent_id'], unique=False)
    op.create_table('currency_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.Unicode(length=3), nullable=True),
    sa.Column('currency', sa.Unicode(length=3), nullable=True),
    sa.Column('rate', sa.Numeric(precision=13, scale=4), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_rate_base_currency'), 'currency_rate', ['base_currency'], unique=False)
    op.create_index(op.f('ix_currency_rate_currency'), 'currency_rate', ['currency'], unique=False)
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=False)
    op.create_table('group_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category_type', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['group_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_category_group_id'), 'group_category', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_category_logo'), 'group_category', ['logo'], unique=False)
    op.create_index(op.f('ix_group_category_name'), 'group_category', ['name'], unique=False)
    op.create_index(op.f('ix_group_category_parent_id'), 'group_category', ['parent_id'], unique=False)
    op.create_table('group_currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('symbol', sa.String(length=3), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_currency_date_modified'), 'group_currency', ['date_modified'], unique=False)
    op.create_index(op.f('ix_group_currency_group_id'), 'group_currency', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_currency_name'), 'group_currency', ['name'], unique=False)
    op.create_index(op.f('ix_group_currency_symbol'), 'group_currency', ['symbol'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=True),
    sa.Column('last_name', sa.String(length=256), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('super_user', sa.Boolean(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_group_id'), 'user', ['group_id'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['group_currency.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_currency_id'), 'account', ['currency_id'], unique=False)
    op.create_index(op.f('ix_account_name'), 'account', ['name'], unique=False)
    op.create_index(op.f('ix_account_user_id'), 'account', ['user_id'], unique=False)
    op.create_table('app',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_name'), 'app', ['name'], unique=False)
    op.create_index(op.f('ix_app_secret'), 'app', ['secret'], unique=False)
    op.create_index(op.f('ix_app_user_id'), 'app', ['user_id'], unique=False)
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=13, scale=4), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('record_type', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['group_category.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['group_currency.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_account_id'), 'record', ['account_id'], unique=False)
    op.create_index(op.f('ix_record_category_id'), 'record', ['category_id'], unique=False)
    op.create_index(op.f('ix_record_currency_id'), 'record', ['currency_id'], unique=False)
    op.create_index(op.f('ix_record_date'), 'record', ['date'], unique=False)
    op.create_index(op.f('ix_record_description'), 'record', ['description'], unique=False)
    op.create_index(op.f('ix_record_user_id'), 'record', ['user_id'], unique=False)
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['app.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_app_id'), 'token', ['app_id'], unique=False)
    op.create_index(op.f('ix_token_token'), 'token', ['token'], unique=False)
    op.create_index(op.f('ix_token_user_id'), 'token', ['user_id'], unique=False)
    op.create_table('record_tag',
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record_tag')
    op.drop_index(op.f('ix_token_user_id'), table_name='token')
    op.drop_index(op.f('ix_token_token'), table_name='token')
    op.drop_index(op.f('ix_token_app_id'), table_name='token')
    op.drop_table('token')
    op.drop_index(op.f('ix_record_user_id'), table_name='record')
    op.drop_index(op.f('ix_record_description'), table_name='record')
    op.drop_index(op.f('ix_record_date'), table_name='record')
    op.drop_index(op.f('ix_record_currency_id'), table_name='record')
    op.drop_index(op.f('ix_record_category_id'), table_name='record')
    op.drop_index(op.f('ix_record_account_id'), table_name='record')
    op.drop_table('record')
    op.drop_index(op.f('ix_app_user_id'), table_name='app')
    op.drop_index(op.f('ix_app_secret'), table_name='app')
    op.drop_index(op.f('ix_app_name'), table_name='app')
    op.drop_table('app')
    op.drop_index(op.f('ix_account_user_id'), table_name='account')
    op.drop_index(op.f('ix_account_name'), table_name='account')
    op.drop_index(op.f('ix_account_currency_id'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_group_id'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_group_currency_symbol'), table_name='group_currency')
    op.drop_index(op.f('ix_group_currency_name'), table_name='group_currency')
    op.drop_index(op.f('ix_group_currency_group_id'), table_name='group_currency')
    op.drop_index(op.f('ix_group_currency_date_modified'), table_name='group_currency')
    op.drop_table('group_currency')
    op.drop_index(op.f('ix_group_category_parent_id'), table_name='group_category')
    op.drop_index(op.f('ix_group_category_name'), table_name='group_category')
    op.drop_index(op.f('ix_group_category_logo'), table_name='group_category')
    op.drop_index(op.f('ix_group_category_group_id'), table_name='group_category')
    op.drop_table('group_category')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    op.drop_table('group')
    op.drop_index(op.f('ix_currency_rate_currency'), table_name='currency_rate')
    op.drop_index(op.f('ix_currency_rate_base_currency'), table_name='currency_rate')
    op.drop_table('currency_rate')
    op.drop_index(op.f('ix_category_parent_id'), table_name='category')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_logo'), table_name='category')
    op.drop_table('category')
    ### end Alembic commands ###
