"""empty message

Revision ID: 48188d77934
Revises: 13484841a0c
Create Date: 2016-03-10 21:06:25.566002

"""

# revision identifiers, used by Alembic.
revision = '48188d77934'
down_revision = '13484841a0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('colour', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_category_colour'), 'category', ['colour'], unique=False)
    op.add_column('group_category', sa.Column('colour', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_group_category_colour'), 'group_category', ['colour'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_category_colour'), table_name='group_category')
    op.drop_column('group_category', 'colour')
    op.drop_index(op.f('ix_category_colour'), table_name='category')
    op.drop_column('category', 'colour')
    ### end Alembic commands ###
