"""empty message

Revision ID: 4ec51163fa6
Revises: 5211d03d0c
Create Date: 2016-06-11 17:40:28.660680

"""

# revision identifiers, used by Alembic.
revision = '4ec51163fa6'
down_revision = '5211d03d0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transaction', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_transaction_date'), 'transaction', ['date'], unique=False)
    op.create_index(op.f('ix_transaction_description'), 'transaction', ['description'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_description'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_date'), table_name='transaction')
    op.drop_column('transaction', 'description')
    op.drop_column('transaction', 'date')
    ### end Alembic commands ###
