"""empty message

Revision ID: 51dbdb3dd34
Revises: 48188d77934
Create Date: 2016-06-09 07:06:38.061199

"""

# revision identifiers, used by Alembic.
revision = '51dbdb3dd34'
down_revision = '48188d77934'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=13, scale=4), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['group_currency.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_currency_id'), 'transaction', ['currency_id'], unique=False)
    op.create_index(op.f('ix_transaction_source_id'), 'transaction', ['source_id'], unique=False)
    op.create_index(op.f('ix_transaction_target_id'), 'transaction', ['target_id'], unique=False)
    op.create_index(op.f('ix_transaction_user_id'), 'transaction', ['user_id'], unique=False)
    op.add_column('record', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_record_transaction_id'), 'record', ['transaction_id'], unique=False)
    op.create_foreign_key(None, 'record', 'transaction', ['transaction_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.drop_index(op.f('ix_record_transaction_id'), table_name='record')
    op.drop_column('record', 'transaction_id')
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_target_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_source_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_currency_id'), table_name='transaction')
    op.drop_table('transaction')
    ### end Alembic commands ###
