"""empty message

Revision ID: 5211d03d0c
Revises: 51dbdb3dd34
Create Date: 2016-06-09 19:55:19.866976

"""

# revision identifiers, used by Alembic.
revision = '5211d03d0c'
down_revision = '51dbdb3dd34'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('source_account_id', sa.Integer(), nullable=True))
    op.add_column('transaction', sa.Column('target_account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transaction_source_account_id'), 'transaction', ['source_account_id'], unique=False)
    op.create_index(op.f('ix_transaction_target_account_id'), 'transaction', ['target_account_id'], unique=False)
    op.drop_index('ix_transaction_source_id', table_name='transaction')
    op.drop_index('ix_transaction_target_id', table_name='transaction')
    op.drop_constraint('transaction_source_id_fkey', 'transaction', type_='foreignkey')
    op.drop_constraint('transaction_target_id_fkey', 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'account', ['source_account_id'], ['id'])
    op.create_foreign_key(None, 'transaction', 'account', ['target_account_id'], ['id'])
    op.drop_column('transaction', 'source_id')
    op.drop_column('transaction', 'target_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transaction', sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key('transaction_target_id_fkey', 'transaction', 'account', ['target_id'], ['id'])
    op.create_foreign_key('transaction_source_id_fkey', 'transaction', 'account', ['source_id'], ['id'])
    op.create_index('ix_transaction_target_id', 'transaction', ['target_id'], unique=False)
    op.create_index('ix_transaction_source_id', 'transaction', ['source_id'], unique=False)
    op.drop_index(op.f('ix_transaction_target_account_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_source_account_id'), table_name='transaction')
    op.drop_column('transaction', 'target_account_id')
    op.drop_column('transaction', 'source_account_id')
    ### end Alembic commands ###
